// Shared correspondence data layer for cross-tool features
// Extracted from: Crystal Database (93), Herbal Guide (22), Rune Caster (24), Candle Magic (15)
// Total: 154 items
//
// Fields: tool, link, name, emoji, hex (candles only), intentions, element, chakra, planet, zodiac

const CORRESPONDENCE_DATA = [

    // ─── CRYSTALS (93) ──────────────────────────────────────────
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Clear Quartz",
        emoji: "💎",
        intentions: ["Purification","Healing","Intuition"],
        element: "All Elements",
        chakra: "Crown",
        planet: null,
        zodiac: ["All Signs"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Amethyst",
        emoji: "💜",
        intentions: ["Intuition","Protection","Peace","Purification"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Pisces","Virgo","Aquarius","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Rose Quartz",
        emoji: "🌸",
        intentions: ["Love","Healing","Peace"],
        element: "Water",
        chakra: "Heart",
        planet: null,
        zodiac: ["Taurus","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Black Tourmaline",
        emoji: "⚫",
        intentions: ["Protection","Grounding","Purification"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Citrine",
        emoji: "🍋",
        intentions: ["Abundance","Creativity","Courage"],
        element: "Fire",
        chakra: "Solar Plexus",
        planet: null,
        zodiac: ["Aries","Gemini","Leo","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Selenite",
        emoji: "🤍",
        intentions: ["Purification","Intuition","Peace"],
        element: "Air",
        chakra: "Crown",
        planet: null,
        zodiac: ["Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Labradorite",
        emoji: "🌌",
        intentions: ["Intuition","Protection","Creativity"],
        element: "Water",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Leo","Scorpio","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Carnelian",
        emoji: "🧡",
        intentions: ["Courage","Creativity","Abundance"],
        element: "Fire",
        chakra: "Sacral",
        planet: null,
        zodiac: ["Aries","Leo","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Moonstone",
        emoji: "🌙",
        intentions: ["Intuition","Love","Protection"],
        element: "Water",
        chakra: "Crown",
        planet: null,
        zodiac: ["Cancer","Libra","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Hematite",
        emoji: "⚙️",
        intentions: ["Grounding","Protection","Courage"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Aries","Aquarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Lapis Lazuli",
        emoji: "💙",
        intentions: ["Intuition","Courage","Protection"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Sagittarius","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Green Aventurine",
        emoji: "🍀",
        intentions: ["Abundance","Love","Healing"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Aries","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Obsidian",
        emoji: "🖤",
        intentions: ["Protection","Grounding","Purification"],
        element: "Earth/Fire",
        chakra: "Root",
        planet: null,
        zodiac: ["Scorpio","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Tiger's Eye",
        emoji: "🐯",
        intentions: ["Courage","Protection","Abundance"],
        element: "Fire/Earth",
        chakra: "Solar Plexus",
        planet: null,
        zodiac: ["Capricorn","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Amazonite",
        emoji: "🌊",
        intentions: ["Peace","Courage","Protection"],
        element: "Water",
        chakra: "Heart",
        planet: null,
        zodiac: ["Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Garnet",
        emoji: "❤️",
        intentions: ["Love","Courage","Protection"],
        element: "Fire",
        chakra: "Root",
        planet: null,
        zodiac: ["Aquarius","Capricorn","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Fluorite",
        emoji: "🌈",
        intentions: ["Intuition","Protection","Purification"],
        element: "Air/Water",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Pisces","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Turquoise",
        emoji: "💚",
        intentions: ["Protection","Healing","Peace"],
        element: "Air/Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Scorpio","Sagittarius","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Sodalite",
        emoji: "💎",
        intentions: ["Intuition","Peace","Courage"],
        element: "Water/Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Malachite",
        emoji: "💚",
        intentions: ["Protection","Healing","Courage"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Scorpio","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Pyrite",
        emoji: "✨",
        intentions: ["Abundance","Protection","Courage"],
        element: "Fire/Earth",
        chakra: "Solar Plexus",
        planet: null,
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Rhodonite",
        emoji: "🌺",
        intentions: ["Love","Healing","Courage"],
        element: "Fire/Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Smoky Quartz",
        emoji: "💨",
        intentions: ["Grounding","Protection","Purification"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Scorpio","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Aquamarine",
        emoji: "🌊",
        intentions: ["Peace","Courage","Protection"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Aries","Gemini","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Blue Lace Agate",
        emoji: "🩵",
        intentions: ["Communication","Calm","Peace"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Gemini","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Howlite",
        emoji: "🤍",
        intentions: ["Calm","Sleep","Patience"],
        element: "Air",
        chakra: "Crown",
        planet: null,
        zodiac: ["Gemini","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Lepidolite",
        emoji: "💜",
        intentions: ["Anxiety","Transition","Emotional Balance"],
        element: "Water",
        chakra: "Heart",
        planet: null,
        zodiac: ["Libra","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Sunstone",
        emoji: "🌞",
        intentions: ["Joy","Abundance","Confidence"],
        element: "Fire",
        chakra: "Sacral",
        planet: null,
        zodiac: ["Leo","Libra","Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Red Jasper",
        emoji: "🔴",
        intentions: ["Grounding","Strength","Vitality"],
        element: "Fire",
        chakra: "Root",
        planet: null,
        zodiac: ["Aries","Scorpio","Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Orange Calcite",
        emoji: "🟠",
        intentions: ["Creativity","Sexuality","Motivation"],
        element: "Fire",
        chakra: "Sacral",
        planet: null,
        zodiac: ["Cancer","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Celestite",
        emoji: "🌌",
        intentions: ["Angelic Connection","Dreams","Peace"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Gemini","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Shungite",
        emoji: "🖤",
        intentions: ["EMF Protection","Grounding","Purification"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Scorpio","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Kyanite",
        emoji: "💙",
        intentions: ["Alignment","Psychic Ability","Communication"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Aries","Taurus","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Peridot",
        emoji: "💚",
        intentions: ["Abundance","Renewal","Release"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Leo","Virgo","Scorpio","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Bloodstone",
        emoji: "🟢",
        intentions: ["Courage","Vitality","Protection"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Aries","Pisces","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Unakite",
        emoji: "🌿",
        intentions: ["Emotional Healing","Balance","Rebirth"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Scorpio","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Chrysocolla",
        emoji: "🩵",
        intentions: ["Communication","Goddess Energy","Compassion"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Taurus","Gemini","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Prehnite",
        emoji: "🍏",
        intentions: ["Prophecy","Inner Peace","Organization"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Libra","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Iolite",
        emoji: "🔵",
        intentions: ["Intuition","Vision","Inner Journey"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Libra","Sagittarius","Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Larimar",
        emoji: "🌊",
        intentions: ["Goddess Energy","Communication","Tranquility"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Leo","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Charoite",
        emoji: "💜",
        intentions: ["Transformation","Spiritual Sight","Service"],
        element: "Wind",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Sagittarius","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Snowflake Obsidian",
        emoji: "🖤",
        intentions: ["Purity","Balance","Surrender"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Capricorn","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Apache Tears",
        emoji: "🖤",
        intentions: ["Grief","Comfort","Protection"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Aries","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Blue Apatite",
        emoji: "🔵",
        intentions: ["Manifestation","Communication","Motivation"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Gemini","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Pink Calcite",
        emoji: "🩷",
        intentions: ["Unconditional Love","Compassion","Self-Healing"],
        element: "Water",
        chakra: "Heart",
        planet: null,
        zodiac: ["Cancer","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Dalmatian Jasper",
        emoji: "🐾",
        intentions: ["Joy","Playfulness","Loyalty"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Virgo","Gemini"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Moldavite",
        emoji: "🌿",
        intentions: ["Transformation","Cosmic Connection","Acceleration"],
        element: "Storm",
        chakra: "Heart",
        planet: null,
        zodiac: ["Scorpio","All Signs"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Seraphinite",
        emoji: "💚",
        intentions: ["Angelic Contact","Healing","Spiritual Enlightenment"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Sagittarius","Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Peacock Ore",
        emoji: "🦚",
        intentions: ["Joy","Happiness","Creativity"],
        element: "Fire",
        chakra: "All Chakras",
        planet: null,
        zodiac: ["Capricorn","Aquarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Pietersite",
        emoji: "⚡",
        intentions: ["Transformation","Willpower","Psychic Vision"],
        element: "Storm",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Leo","Aquarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Lapis Lazuli",
        emoji: "🌌",
        intentions: ["Intuition","Communication","Truth"],
        element: "Water",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Sagittarius","Aquarius","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Sodalite",
        emoji: "🔵",
        intentions: ["Intuition","Communication","Peace"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Sagittarius","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Moonstone",
        emoji: "🌙",
        intentions: ["Intuition","Feminine Energy","New Beginnings"],
        element: "Water",
        chakra: "Crown",
        planet: null,
        zodiac: ["Cancer","Libra","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Labradorite",
        emoji: "🌀",
        intentions: ["Transformation","Protection","Intuition"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Leo","Scorpio","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Fluorite",
        emoji: "🟩",
        intentions: ["Focus","Protection","Purification"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Capricorn","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Lepidolite",
        emoji: "💜",
        intentions: ["Peace","Healing","Transformation"],
        element: "Water",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Libra","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Malachite",
        emoji: "🌿",
        intentions: ["Transformation","Protection","Abundance"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Capricorn","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Turquoise",
        emoji: "🩵",
        intentions: ["Protection","Communication","Healing"],
        element: "Earth",
        chakra: "Throat",
        planet: null,
        zodiac: ["Sagittarius","Scorpio","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Amazonite",
        emoji: "🌊",
        intentions: ["Communication","Courage","Peace"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Virgo","Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Garnet",
        emoji: "🔴",
        intentions: ["Love","Passion","Grounding"],
        element: "Fire",
        chakra: "Root",
        planet: null,
        zodiac: ["Capricorn","Aquarius","Aries","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Aquamarine",
        emoji: "💧",
        intentions: ["Communication","Courage","Peace"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Gemini","Pisces","Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Rhodonite",
        emoji: "🌸",
        intentions: ["Love","Healing","Forgiveness"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Taurus","Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Sunstone",
        emoji: "☀️",
        intentions: ["Joy","Abundance","Courage"],
        element: "Fire",
        chakra: "Sacral",
        planet: null,
        zodiac: ["Leo","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Prehnite",
        emoji: "💚",
        intentions: ["Peace","Healing","Intuition"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Libra","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Chrysoprase",
        emoji: "🌱",
        intentions: ["Love","Joy","Abundance"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Taurus","Libra","Gemini"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Peridot",
        emoji: "🌿",
        intentions: ["Abundance","Healing","Protection"],
        element: "Earth",
        chakra: "Heart",
        planet: null,
        zodiac: ["Leo","Virgo","Sagittarius","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Blue Kyanite",
        emoji: "🪶",
        intentions: ["Communication","Intuition","Purification"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Taurus","Libra","Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Howlite",
        emoji: "🤍",
        intentions: ["Peace","Patience","Purification"],
        element: "Air",
        chakra: "Crown",
        planet: null,
        zodiac: ["Gemini","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Rhodochrosite",
        emoji: "🌺",
        intentions: ["Love","Healing","Self-Love"],
        element: "Fire",
        chakra: "Heart",
        planet: null,
        zodiac: ["Scorpio","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Kunzite",
        emoji: "🩷",
        intentions: ["Love","Peace","Healing"],
        element: "Water",
        chakra: "Heart",
        planet: null,
        zodiac: ["Taurus","Leo","Libra","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Iolite",
        emoji: "🔮",
        intentions: ["Intuition","Transformation","Inner Vision"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Taurus","Libra","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Tanzanite",
        emoji: "💜",
        intentions: ["Spiritual Growth","Transformation","Communication"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Sagittarius","Aries","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Topaz (Blue)",
        emoji: "🩵",
        intentions: ["Communication","Intuition","Truth"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Sagittarius","Virgo","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Larimar",
        emoji: "🌊",
        intentions: ["Peace","Communication","Healing"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Charoite",
        emoji: "🔮",
        intentions: ["Transformation","Spiritual Growth","Healing"],
        element: "Water",
        chakra: "Crown",
        planet: null,
        zodiac: ["Scorpio","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Sugilite",
        emoji: "💜",
        intentions: ["Spiritual Protection","Healing","Love"],
        element: "Air",
        chakra: "Crown",
        planet: null,
        zodiac: ["Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Shungite",
        emoji: "⚫",
        intentions: ["Protection","Purification","Grounding"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Scorpio","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen", "Chaos Magick"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Selenite",
        emoji: "🤍",
        intentions: ["Purification","Intuition","Peace"],
        element: "Air",
        chakra: "Crown",
        planet: null,
        zodiac: ["Taurus","Cancer"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Chalcopyrite",
        emoji: "✨",
        intentions: ["Abundance","Creativity","Confidence"],
        element: "Fire",
        chakra: "Crown",
        planet: null,
        zodiac: ["Capricorn","Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Aragonite",
        emoji: "🌿",
        intentions: ["Grounding","Healing","Patience"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Orange Calcite",
        emoji: "🍊",
        intentions: ["Creativity","Joy","Sexuality"],
        element: "Fire",
        chakra: "Sacral",
        planet: null,
        zodiac: ["Cancer","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Green Calcite",
        emoji: "💚",
        intentions: ["Healing","Love","Abundance"],
        element: "Fire",
        chakra: "Heart",
        planet: null,
        zodiac: ["Cancer"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Apatite",
        emoji: "💙",
        intentions: ["Intuition","Communication","Manifestation"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Gemini","Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Scolecite",
        emoji: "🌟",
        intentions: ["Peace","Spiritual Growth","Dreamwork"],
        element: "Air",
        chakra: "Crown",
        planet: null,
        zodiac: ["Capricorn"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Chrysocolla",
        emoji: "🌊",
        intentions: ["Communication","Feminine Energy","Peace"],
        element: "Water",
        chakra: "Throat",
        planet: null,
        zodiac: ["Gemini","Virgo","Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Azurite",
        emoji: "🔵",
        intentions: ["Intuition","Spiritual Growth","Communication"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Hemimorphite",
        emoji: "🩵",
        intentions: ["Communication","Spiritual Growth","Joy"],
        element: "Air",
        chakra: "Throat",
        planet: null,
        zodiac: ["Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Spinel",
        emoji: "💎",
        intentions: ["Vitality","Grounding","Renewal"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Aries","Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Smithsonite",
        emoji: "🌸",
        intentions: ["Healing","Peace","Love"],
        element: "Water",
        chakra: "Heart",
        planet: null,
        zodiac: ["Virgo","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Ulexite",
        emoji: "🔮",
        intentions: ["Intuition","Clarity","Vision"],
        element: "Air",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Gemini"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Vanadinite",
        emoji: "🔴",
        intentions: ["Creativity","Vitality","Manifestation"],
        element: "Fire",
        chakra: "Sacral",
        planet: null,
        zodiac: ["Virgo","Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Sphalerite",
        emoji: "⚡",
        intentions: ["Grounding","Vitality","Manifestation"],
        element: "Earth",
        chakra: "Root",
        planet: null,
        zodiac: ["Gemini"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Heathen"]
    },
    {
        tool: "Crystal",
        link: "../html/crystal-database.html",
        name: "Magnesite",
        emoji: "🤍",
        intentions: ["Peace","Intuition","Healing"],
        element: "Fire",
        chakra: "Third Eye",
        planet: null,
        zodiac: ["Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch"]
    },

    // ─── HERBS (22) ─────────────────────────────────────────────
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Lavender",
        emoji: "💜",
        intentions: ["Peace","Sleep","Love","Purification"],
        element: "Air",
        chakra: null,
        planet: "Mercury",
        zodiac: ["Gemini","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Rosemary",
        emoji: "🌿",
        intentions: ["Protection","Purification","Healing","Love"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: ["Aries","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Ceremonial"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Mugwort",
        emoji: "🌙",
        intentions: ["Divination","Sleep","Protection","Purification"],
        element: "Earth",
        chakra: null,
        planet: "Moon",
        zodiac: ["Cancer","Pisces"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Heathen", "Chaos Magick"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Sage",
        emoji: "🍃",
        intentions: ["Purification","Protection","Healing","Prosperity"],
        element: "Air",
        chakra: null,
        planet: "Jupiter",
        zodiac: ["Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Ceremonial"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Chamomile",
        emoji: "🌼",
        intentions: ["Peace","Sleep","Healing","Prosperity"],
        element: "Water",
        chakra: null,
        planet: "Sun",
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Basil",
        emoji: "🌱",
        intentions: ["Love","Prosperity","Protection","Purification"],
        element: "Fire",
        chakra: null,
        planet: "Mars",
        zodiac: ["Aries","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Peppermint",
        emoji: "🍵",
        intentions: ["Purification","Healing","Prosperity","Sleep"],
        element: "Air",
        chakra: null,
        planet: "Mercury",
        zodiac: ["Gemini","Virgo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Yarrow",
        emoji: "🌸",
        intentions: ["Protection","Courage","Healing","Divination"],
        element: "Water",
        chakra: null,
        planet: "Venus",
        zodiac: ["Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Heathen"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Bay Laurel",
        emoji: "🍂",
        intentions: ["Protection","Purification","Divination","Prosperity"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Druidry", "Ceremonial"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Thyme",
        emoji: "🌿",
        intentions: ["Courage","Healing","Purification","Sleep"],
        element: "Water",
        chakra: null,
        planet: "Venus",
        zodiac: ["Taurus","Libra"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Druidry"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Cinnamon",
        emoji: "🪵",
        intentions: ["Prosperity","Love","Protection","Healing"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: ["Aries","Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Ceremonial"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Lemon Balm",
        emoji: "🍋",
        intentions: ["Love","Healing","Peace","Prosperity"],
        element: "Water",
        chakra: null,
        planet: "Moon",
        zodiac: ["Cancer"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Calendula",
        emoji: "🌻",
        intentions: ["Healing","Protection","Divination","Love"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Druidry"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Nettle",
        emoji: "🌿",
        intentions: ["Protection","Healing","Banishing","Courage"],
        element: "Fire",
        chakra: null,
        planet: "Mars",
        zodiac: ["Aries","Scorpio"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Heathen"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Echinacea",
        emoji: "🌺",
        intentions: ["Healing","Protection","Prosperity"],
        element: "Earth",
        chakra: null,
        planet: "Jupiter",
        zodiac: ["Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Elderflower",
        emoji: "🌸",
        intentions: ["Protection","Healing","Purification","Prosperity"],
        element: "Water",
        chakra: null,
        planet: "Venus",
        zodiac: ["Pisces","Cancer"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Heathen"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Dandelion",
        emoji: "🌼",
        intentions: ["Divination","Prosperity","Healing","Purification"],
        element: "Air",
        chakra: null,
        planet: "Jupiter",
        zodiac: ["Sagittarius"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Druidry"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "St. John's Wort",
        emoji: "☀",
        intentions: ["Protection","Healing","Banishing","Courage"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Heathen"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Catnip",
        emoji: "🐱",
        intentions: ["Love","Peace","Sleep","Courage"],
        element: "Water",
        chakra: null,
        planet: "Venus",
        zodiac: ["Taurus"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Clove",
        emoji: "🌰",
        intentions: ["Protection","Love","Prosperity","Banishing"],
        element: "Fire",
        chakra: null,
        planet: "Jupiter",
        zodiac: ["Aries"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Ceremonial"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Frankincense",
        emoji: "🪔",
        intentions: ["Purification","Protection","Divination","Healing"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: ["Leo"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Ceremonial"]
    },
    {
        tool: "Herb",
        link: "../html/herbal-database.html",
        name: "Myrrh",
        emoji: "💧",
        intentions: ["Protection","Purification","Healing","Banishing"],
        element: "Water",
        chakra: null,
        planet: "Moon",
        zodiac: ["Cancer"],
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Ceremonial"]
    },

    // ─── RUNES (24) ─────────────────────────────────────────────
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Fehu",
        emoji: "ᚠ",
        intentions: ["Wealth","Abundance","Prosperity","Success"],
        element: "Fire",
        chakra: null,
        planet: "Mars",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Uruz",
        emoji: "ᚢ",
        intentions: ["Strength","Vitality","Courage","Primal Power"],
        element: "Earth",
        chakra: null,
        planet: "Mars",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Thurisaz",
        emoji: "ᚦ",
        intentions: ["Gateway","Protection","Defense","Breakthrough"],
        element: "Fire",
        chakra: null,
        planet: "Mars",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Ansuz",
        emoji: "ᚨ",
        intentions: ["Communication","Wisdom","Divine Inspiration","Signals"],
        element: "Air",
        chakra: null,
        planet: "Mercury",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Raidho",
        emoji: "ᚱ",
        intentions: ["Journey","Movement","Quest","Right Action"],
        element: "Air",
        chakra: null,
        planet: "Mercury",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Kenaz",
        emoji: "ᚲ",
        intentions: ["Knowledge","Creativity","Inspiration","Illumination"],
        element: "Fire",
        chakra: null,
        planet: "Venus",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Gebo",
        emoji: "ᚷ",
        intentions: ["Gift","Partnership","Exchange","Balance"],
        element: "Air",
        chakra: null,
        planet: "Venus",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Wunjo",
        emoji: "ᚹ",
        intentions: ["Joy","Harmony","Success","Fellowship"],
        element: "Earth",
        chakra: null,
        planet: "Jupiter",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Hagalaz",
        emoji: "ᚺ",
        intentions: ["Disruption","Natural Forces","Cleansing","Transformation"],
        element: "Ice",
        chakra: null,
        planet: "Uranus",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Nauthiz",
        emoji: "ᚾ",
        intentions: ["Need","Constraint","Necessity","Resilience"],
        element: "Fire",
        chakra: null,
        planet: "Saturn",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Isa",
        emoji: "ᛁ",
        intentions: ["Stillness","Ice","Standstill","Preservation"],
        element: "Ice",
        chakra: null,
        planet: "Saturn",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Jera",
        emoji: "ᛃ",
        intentions: ["Harvest","Cycles","Reward","Right Timing"],
        element: "Earth",
        chakra: null,
        planet: "Earth",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Eihwaz",
        emoji: "ᛇ",
        intentions: ["Endurance","Yew Tree","Death-Life","Transformation"],
        element: "All",
        chakra: null,
        planet: "Pluto",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Perthro",
        emoji: "ᛈ",
        intentions: ["Mystery","Fate","Hidden Things","Initiation"],
        element: "Water",
        chakra: null,
        planet: "Neptune",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Algiz",
        emoji: "ᛉ",
        intentions: ["Protection","Higher Self","Divine Connection","Sanctuary"],
        element: "Air",
        chakra: null,
        planet: "Neptune",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Sowilo",
        emoji: "ᛊ",
        intentions: ["Success","Wholeness","Sun","Life Force"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Tiwaz",
        emoji: "ᛏ",
        intentions: ["Justice","Honor","Sacrifice","Warrior Spirit"],
        element: "Air",
        chakra: null,
        planet: "Mars",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Berkano",
        emoji: "ᛒ",
        intentions: ["Birth","Growth","Fertility","Nurturing"],
        element: "Earth",
        chakra: null,
        planet: "Moon",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Ehwaz",
        emoji: "ᛖ",
        intentions: ["Partnership","Trust","Movement","Horse"],
        element: "Earth",
        chakra: null,
        planet: "Mercury",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Mannaz",
        emoji: "ᛗ",
        intentions: ["Humanity","Self","Community","Intelligence"],
        element: "Air",
        chakra: null,
        planet: "Jupiter",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Laguz",
        emoji: "ᛚ",
        intentions: ["Flow","Water","Intuition","Emotion"],
        element: "Water",
        chakra: null,
        planet: "Moon",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Ingwaz",
        emoji: "ᛝ",
        intentions: ["Potential","Gestation","Fertility","Internal Growth"],
        element: "Earth",
        chakra: null,
        planet: "Earth",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Dagaz",
        emoji: "ᛞ",
        intentions: ["Dawn","Breakthrough","Awakening","Transformation"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },
    {
        tool: "Rune",
        link: "../html/rune-caster.html",
        name: "Othala",
        emoji: "ᛟ",
        intentions: ["Heritage","Home","Ancestral Property","Legacy"],
        element: "Earth",
        chakra: null,
        planet: "Saturn",
        zodiac: null,
        traditions: ["Heathen", "Eclectic", "Ceremonial"]
    },

    // ─── CANDLE COLORS (15) ─────────────────────────────────────
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "White",
        emoji: "🕯️",
        hex: "#f8f4e8",
        intentions: ["Purification","New Beginnings","Peace","Clarity","Truth","Protection","Spiritual Growth"],
        element: "Spirit",
        chakra: null,
        planet: "Moon",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch", "Ceremonial", "Druidry", "Heathen", "Chaos Magick"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Black",
        emoji: "🕯️",
        hex: "#1c1c1c",
        intentions: ["Protection","Banishing","Binding","Shadow Work","Reversal","Grounding"],
        element: "Earth",
        chakra: null,
        planet: "Saturn",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Heathen", "Chaos Magick", "Ceremonial"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Red",
        emoji: "🕯️",
        hex: "#cc0000",
        intentions: ["Love","Passion","Courage","Strength","Vitality","Power","Protection"],
        element: "Fire",
        chakra: null,
        planet: "Mars",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Heathen", "Chaos Magick", "Ceremonial"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Pink",
        emoji: "🕯️",
        hex: "#ff8fab",
        intentions: ["Love","Self-Love","Friendship","Healing","Compassion","Peace"],
        element: "Water",
        chakra: null,
        planet: "Venus",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Kitchen Witch", "Green Witch"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Orange",
        emoji: "🕯️",
        hex: "#ff7c2a",
        intentions: ["Success","Creativity","Abundance","Confidence","Clarity","Attraction"],
        element: "Fire",
        chakra: null,
        planet: "Mercury / Sun",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Chaos Magick"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Yellow",
        emoji: "🕯️",
        hex: "#f9c74f",
        intentions: ["Clarity","Creativity","Confidence","Success","Peace","Spiritual Growth"],
        element: "Air",
        chakra: null,
        planet: "Mercury",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Ceremonial", "Kitchen Witch"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Green",
        emoji: "🕯️",
        hex: "#2d8a4e",
        intentions: ["Abundance","Healing","Growth","Love","Peace","Spiritual Growth"],
        element: "Earth",
        chakra: null,
        planet: "Venus",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry", "Kitchen Witch"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Light Blue",
        emoji: "🕯️",
        hex: "#87ceeb",
        intentions: ["Peace","Healing","Clarity","Protection","Spiritual Growth"],
        element: "Water",
        chakra: null,
        planet: "Moon",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Ceremonial", "Druidry"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Dark Blue",
        emoji: "🕯️",
        hex: "#1a237e",
        intentions: ["Intuition","Spiritual Growth","Clarity","Power","Protection"],
        element: "Water",
        chakra: null,
        planet: "Jupiter / Saturn",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Ceremonial", "Heathen"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Purple",
        emoji: "🕯️",
        hex: "#7b2d8b",
        intentions: ["Power","Spiritual Growth","Intuition","Abundance","Protection","Healing"],
        element: "Spirit",
        chakra: null,
        planet: "Jupiter / Neptune",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Ceremonial", "Chaos Magick"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Brown",
        emoji: "🕯️",
        hex: "#8b5e3c",
        intentions: ["Grounding","Protection","Abundance","Healing"],
        element: "Earth",
        chakra: null,
        planet: "Saturn / Earth",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Druidry"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Silver",
        emoji: "🕯️",
        hex: "#c0c0c0",
        intentions: ["Intuition","Spiritual Growth","Peace","Protection","Clarity"],
        element: "Water",
        chakra: null,
        planet: "Moon",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Ceremonial", "Druidry"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Gold",
        emoji: "🕯️",
        hex: "#d4a017",
        intentions: ["Success","Abundance","Power","Confidence","Spiritual Growth"],
        element: "Fire",
        chakra: null,
        planet: "Sun",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Ceremonial", "Druidry"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Gray",
        emoji: "🕯️",
        hex: "#9e9e9e",
        intentions: ["Protection","Clarity","Banishing","Peace","Grounding"],
        element: "Spirit",
        chakra: null,
        planet: "Mercury / Saturn",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Heathen", "Ceremonial"]
    },
    {
        tool: "Candle",
        link: "../html/candle-magic.html",
        name: "Lavender",
        emoji: "🕯️",
        hex: "#9b72cf",
        intentions: ["Spiritual Growth","Peace","Healing","Intuition","Clarity"],
        element: "Air",
        chakra: null,
        planet: "Mercury / Neptune",
        zodiac: null,
        traditions: ["Wiccan", "Eclectic", "Green Witch", "Kitchen Witch"]
    }

];